# Generated by Django 5.1 on 2024-09-01 09:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1ffdf92d-13a9-4e5b-a234-a9a2011ec0b3'), editable=False, primary_key=True, serialize=False),
        ),
    ]
