# Generated by Django 5.1 on 2024-09-02 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
