# Generated by Django 5.1 on 2024-09-02 16:57

from django.db import migrations


def create_default_groups(apps, schema_editor):
    group = apps.get_model('auth', 'Group')

    groups = ['Manager', 'Developer', 'QA']

    for group_name in groups:
        group.objects.get_or_create(name=group_name)

class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_members'),
    ]

    operations = [
        migrations.RunPython(create_default_groups)
    ]
